### ISSUE TITLE
Shuffle, download and seek commands, lyrics improvement, display likes and dislikes

### ISSUE THREAD

**Issue by snowdqdzq** [Spimy/muse#9]
Hi :)

1 - Make a shuffle command

2 - If the lyrics of the command exceeds 2000 characters it sends the end of the lyrics in another embed.

3 - A seek command example: !seek 1:20

The bot goes 1 minute and 20 seconds from the current music

4 - Displays dislikes, likes, comments in the now-playing command

5 - A command to download the current music or a specified music.

6 - A repeat command that repeats current music.
💙  Thanks for the bot

**Comment by Spimy** [comment]
This music bot was intended for people to learn from and extend upon it by people. You should try to implement at least number 1 and 4 yourself. As for number 3, it is not possible without the use of lavalink which I am not using and have no plans to move to it either. 
I will keep number 2 and 5 in mind for the next update.

P.S. Please use meaningful issue titles instead of simply "SUGGESTION" or "BUG"

**Comment by Spimy** [comment]
Hi, this version of the bot will no longer be maintained. Instead, please check out https://github.com/Spimy/muse-cli
